branch-defaults:
  default:
    environment: udagram-api-dev
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  branch: null
  repository: null
  udagram-api-dev: null
global:
  application_name: udagram-api
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023/6.0.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
